---

- name: Upload Flannel manifest
  template:
    src: flannel.yaml
    dest: /root/flannel.yaml
    backup: yes
  tags:
    - cni

- name: Apply uploaded manifest
  k8s:
    src: /root/flannel.yaml
    state: present
  tags:
    - cni
