---

- name: Upload Weave manifest
  template:
    src: weave.yaml
    dest: /root/weave.yaml
    backup: yes
  tags:
    - cni

- name: Apply uploaded manifest
  k8s:
    src: /root/weave.yaml
    state: present
  tags:
    - cni
