---

- name: Upload Weave manifest
  template:
    src: weave-{{ weave_version.split('.')[:2] | join('.') }}.yaml
    dest: /root/weave.yaml
    backup: yes
  tags:
    - cni

- name: Apply uploaded manifest
  k8s:
    src: /root/weave.yaml
    state: present
  tags:
    - cni
