---

- name: Gather facts from all servers
  hosts: all
  tasks: []

- name: Select one Kubernetes master for initial tasks
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create hostgroup k8s_initial_master
      add_host:
        name: "{{ groups['masters'][0] }}"
        groups: k8s_initial_master

#
# Install basic software
#

- import_playbook: init/main.yml

#
# Setup loadbalancers
# 

- import_playbook: loadbalancers/main.yml

#
# Generate, fetch and deploy certificates
#

- import_playbook: bootstrap/certificates/main.yml

#
# Deploy bootstrap token
#

- import_playbook: bootstrap/token/main.yml

#
# Deploy encryption key
#

- import_playbook: bootstrap/encryption/main.yml

#
# Generate, fetch and deploy kubeconfig
#

- import_playbook: bootstrap/kubeconfigs/main.yml

#
# Setup CoreOS ETCD 
#

- import_playbook: etcd/main.yml

#
# Deploy core components and setup nodes
#

- import_playbook: core/nodes/main.yml

#
# Deploy Weave CNI plugin
#

- import_playbook: core/weave/main.yml

#
# Deploy CoreDNS
#

- import_playbook: core/coredns/main.yml

#
# Deploy Nginx INC. ingress controller
#

- import_playbook: core/ingress/main.yml

#
# Deploy Metrics Server
#

- import_playbook: core/metrics_server/main.yml
