---

- name: Gather facts from all servers
  hosts: all
  tasks: []

#
# Install basic software on all servers in cluster and prepare Kubernetes nodes
#

- import_playbook: init/main.yml

#
# Generate, fetch and deploy certificates
#

- import_playbook: bootstrap/certificates/main.yml

#
# Deploy bootstrap token
#

- import_playbook: bootstrap/token/main.yml

#
# Deploy encryption key
#

- import_playbook: bootstrap/encryption/main.yml

#
# Setup CoreOS ETCD 
#

- import_playbook: etcd/main.yml

#
# Deploy core components and setup Kubernetes nodes
#

- import_playbook: core/nodes/main.yml

#
# Deploy CNI plugin
#

- import_playbook: core/cni/main.yml

#
# Deploy CoreDNS
#

- import_playbook: core/coredns/main.yml

#
# Deploy Nginx INC. ingress controller
#

- import_playbook: core/ingress/main.yml

#
# Deploy Metrics Server
#

- import_playbook: core/metrics_server/main.yml

#
# Deploy NodeLocalDNS cache
#

- import_playbook: addons/nodelocaldns/main.yml
