---

- name: Gather facts from all servers
  hosts: all
  tasks: []

#
# Install basic software on all servers in cluster and prepare Kubernetes nodes
#

- import_playbook: init/main.yml

#
# Generate and fetch certificates
#

- import_playbook: certificates/generate.yml
- import_playbook: certificates/fetch.yml

#
# Setup CoreOS ETCD 
#

- import_playbook: etcd/main.yml

#
# Deploy core components and setup Kubernetes nodes
#

- import_playbook: core/nodes/masters.yml
- import_playbook: core/nodes/workers.yml
- import_playbook: core/nodes/labels.yml

#
# Deploy Kubernetes Proxy
#

- import_playbook: core/proxy/main.yml

#
# Deploy CNI plugin
#

- import_playbook: core/cni/main.yml

#
# Deploy CoreDNS
#

- import_playbook: core/coredns/main.yml

#
# Deploy Nginx INC. ingress controller
#

- import_playbook: core/ingress/main.yml

#
# Deploy Metrics Server
#

- import_playbook: addons/metrics_server/main.yml

#
# Deploy NodeLocalDNS cache
#

- import_playbook: addons/nodelocaldns/main.yml
