---

- name: Fetch frontproxy related certificates
  slurp:
    src: "/etc/ssl/kubernetes/{{ item }}"
  register: frontproxy_certificates
  loop:
    - front-proxy-ca.crt
    - front-proxy-ca.key
    - front-proxy-ca.csr
    - front-proxy-client.crt
    - front-proxy-client.key
    - front-proxy-client.csr
  tags:
    - k8s_fetch_crt
    - k8s_fetch_crt.frontproxy
