---

- name: Fetch Kubernetes related certificates
  slurp:
    src: "/etc/ssl/kubernetes/{{ item }}"
  register: kubernetes_certificates
  loop:
    - admin.crt
    - admin.key
    - admin.csr
    - apiserver.crt
    - apiserver.key
    - apiserver.csr
    - apiserver-kubelet-client.crt
    - apiserver-kubelet-client.key
    - apiserver-kubelet-client.csr
    - ca.crt
    - ca.key
    - ca.csr
    - controller-manager.crt
    - controller-manager.key
    - controller-manager.csr
    - kube-proxy.crt
    - kube-proxy.key
    - kube-proxy.csr
    - sa.crt
    - sa.key
    - sa.csr
    - scheduler.crt
    - scheduler.key
    - scheduler.csr
  tags:
    - k8s_fetch_crt
    - k8s_fetch_crt.kubernetes
