---

- name: Fetch generated CA certificates and keys
  slurp:
    src: "/etc/kubernetes/pki/{{ item }}"
  register: k8s_ca_certificates
  loop:
    - ca.crt
    - ca.csr
    - ca.key
    - front-proxy-ca.crt
    - front-proxy-ca.key
    - front-proxy-ca.csr
    - sa.crt
    - sa.key
    - etcd/ca.crt
    - etcd/ca.key
    - etcd/ca.csr
  tags:
    - k8s_fetch_crt

- name: Fetch ETCD certificates and keys
  slurp:
    src: "/etc/kubernetes/pki/{{ item }}"
  register: etcd_certificates
  loop:
    - etcd/ca.crt
    - etcd/ca.key
    - etcd/ca.csr
    - etcd/server.crt
    - etcd/server.key
    - etcd/server.csr
    - etcd/peer.crt
    - etcd/peer.key
    - etcd/peer.csr
    - etcd/healthcheck-client.crt
    - etcd/healthcheck-client.key
    - etcd/healthcheck-client.csr
    - apiserver-etcd-client.crt
    - apiserver-etcd-client.key
    - apiserver-etcd-client.csr
  tags:
    - k8s_fetch_crt

- name: Fetch frontproxy certificates and keys
  slurp:
    src: "/etc/kubernetes/pki/{{ item }}"
  register: frontproxy_certificates
  loop:
    - front-proxy-client.crt
    - front-proxy-client.key
    - front-proxy-client.csr
  tags:
    - k8s_fetch_crt
