---

- name: Fetch Kubernetes masters certificates
  slurp:
    src: /etc/ssl/kubernetes/{{ item }}.crt
  register: kubernetes_masters_certificates
  loop: "{{ groups[masters_group_name] }}"
  tags:
    - k8s_fetch_crt
    - k8s_fetch_crt.masters

- name: Fetch Kubernetes masters keys
  slurp:
    src: /etc/ssl/kubernetes/{{ item }}.key
  register: kubernetes_masters_keys
  loop: "{{ groups[masters_group_name] }}"
  tags:
    - k8s_fetch_crt
    - k8s_fetch_crt.masters

- name: Fetch Kubernetes masters csrs
  slurp:
    src: /etc/ssl/kubernetes/{{ item }}.csr
  register: kubernetes_masters_csrs
  loop: "{{ groups[masters_group_name] }}"
  tags:
    - k8s_fetch_crt
    - k8s_fetch_crt.masters
