---

- name: Get content of Kubernetes CA certificate
  slurp:
    src: /etc/ssl/kubernetes/ca.crt
  register: kubernetes_ca_crt
  tags:
    - k8s_generate_kubeconfig

- name: Get content of Kubernetes admin certificate
  slurp:
    src: /etc/ssl/kubernetes/admin.crt
  register: kubernetes_admin_crt
  tags:
    - k8s_generate_kubeconfig

- name: Get content of Kubernetes admin key
  slurp:
    src: /etc/ssl/kubernetes/admin.key
  register: kubernetes_admin_key
  tags:
    - k8s_generate_kubeconfig

- name: Get content of Kubernetes Controller Manager certificate
  slurp:
    src: /etc/ssl/kubernetes/controller-manager.crt
  register: kubernetes_controller_manager_crt
  tags:
    - k8s_generate_kubeconfig

- name: Get content of Kubernetes Controller Manager key
  slurp:
    src: /etc/ssl/kubernetes/controller-manager.key
  register: kubernetes_controller_manager_key
  tags:
    - k8s_generate_kubeconfig

- name: Get content of Kubernetes Proxy certificate
  slurp:
    src: /etc/ssl/kubernetes/kube-proxy.crt
  register: kubernetes_proxy_crt
  tags:
    - k8s_generate_kubeconfig

- name: Get content of Kubernetes Proxy key
  slurp:
    src: /etc/ssl/kubernetes/kube-proxy.key
  register: kubernetes_proxy_key
  tags:
    - k8s_generate_kubeconfig

- name: Get content of Kubernetes Scheduler certificate
  slurp:
    src: /etc/ssl/kubernetes/scheduler.crt
  register: kubernetes_scheduler_crt
  tags:
    - k8s_generate_kubeconfig

- name: Get content of Kubernetes Scheduler key
  slurp:
    src: /etc/ssl/kubernetes/scheduler.key
  register: kubernetes_scheduler_key
  tags:
    - k8s_generate_kubeconfig

- name: Generate common kubeconfigs
  template:
    src: "{{ item }}"
    dest: "/var/lib/kubernetes/{{ item }}"
    mode: 0644
    backup: yes
  loop:
    - admin.kubeconfig
    - bootstrap.kubeconfig
    - kube-controller-manager.kubeconfig
    - kube-proxy.kubeconfig
    - kube-scheduler.kubeconfig
    - remote.kubeconfig
  tags:
    - k8s_generate_kubeconfig

- name: Generate root user kubeconfig for cluster management
  template:
    src: remote.kubeconfig
    dest: /root/.kube/config
    mode: 0600
  tags:
    - k8s_generate_kubeconfig
