---

- name: Upload nodelocaldns manifest
  template:
    src: nodelocaldns.yaml
    dest: /root/nodelocaldns.yaml
    backup: yes
  tags:
    - nodelocaldns

- name: Apply uploaded manifest
  k8s:
    src: /root/nodelocaldns.yaml
    state: present
  tags:
    - nodelocaldns
