---

- name: Create ETCD user
  user:
    name: etcd
    shell: /sbin/nologin
    home: /var/lib/etcd
  tags:
    - etcd
    - etcd.install

- name: Create ETCD data directory
  file:
    path: /var/lib/etcd
    state: directory
    mode: 0755
    owner: etcd
    group: etcd
  tags:
    - etcd
    - etcd.install

- name: Get ETCD binaries
  unarchive:
    src: https://storage.googleapis.com/etcd/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
    dest: /usr/bin
    extra_opts:
    - --strip=1
    - --wildcards
    - '*/{{ item }}'
    remote_src: yes
  loop:
    - etcd
    - etcdctl
  notify: restart etcd
  tags:
    - etcd
    - etcd.install

- name: Upload ETCD configuration
  template:
    src: etcd.conf
    dest: /etc/etcd/etcd.conf
  notify: restart etcd
  tags:
    - etcd
    - etcd.conf

- name: Create systemd directory
  file:
    path: /etc/systemd/system/etcd.service.d
    state: directory
    mode: 0755
  tags:
    - etcd
    - etcd.conf

- name: Upload systemd modification
  copy:
    src: custom.conf
    dest: /etc/systemd/system/etcd.service.d/custom.conf
  notify: restart etcd
  tags:
    - etcd
    - etcd.conf

- name: Start and enable ETCD
  systemd:
    name: etcd
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - etcd
    - etcd.start
