---

- name: Deploy CA certificates
  copy:
    content: "{{ item.content | b64decode }}"
    dest: "/etc/ssl/kubernetes/{{ item.item }}"
    mode: 0644
  loop: "{{ hostvars[groups[masters_group_name][0]].k8s_ca_certificates.results }}"
  tags:
    - etcd
    - etcd.certificates

- name: Deploy ETCD certificates
  copy:
    content: "{{ item.content | b64decode }}"
    dest: "/etc/ssl/kubernetes/{{ item.item }}"
    mode: 0644
  loop: "{{ hostvars[groups[masters_group_name][0]].etcd_certificates.results }}"
  tags:
    - etcd
    - etcd.certificates

- name: Create ETCD user
  user:
    name: etcd
    shell: /sbin/nologin
    home: /var/lib/etcd
  tags:
    - etcd
    - etcd.install

- name: Create ETCD configuration and data directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: etcd
    group: etcd
  loop:
    - /var/lib/etcd
    - /etc/etcd
  tags:
    - etcd
    - etcd.install

- name: Get ETCD binaries
  unarchive:
    src: https://storage.googleapis.com/etcd/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
    dest: /usr/bin
    extra_opts:
    - --strip=1
    - --wildcards
    - '*/{{ item }}'
    remote_src: yes
  loop:
    - etcd
    - etcdctl
  notify: restart etcd
  tags:
    - etcd
    - etcd.install

- name: Upload ETCD configuration
  template:
    src: etcd.conf
    dest: /etc/etcd/etcd.conf
  notify: restart etcd
  tags:
    - etcd
    - etcd.conf

- name: Upload systemd unit file
  copy:
    src: etcd-{{ etcd_version.split(".")[:2] | join(".") }}.service
    dest: /etc/systemd/system/etcd.service
  notify: restart etcd
  tags:
    - etcd
    - etcd.conf

- name: Start and enable ETCD
  systemd:
    name: etcd
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - etcd
    - etcd.start
