---

- name: Get package facts
  package_facts:
    manager: auto

- name: Include OS specific tasks
  include_tasks: "{{ item }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - default.yml
  loop: "{{ q('first_found', params, errors='ignore') }}"

- name: Create directories for certificates
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/kubernetes/pki
    - /etc/kubernetes/pki/etcd
  tags:
    - software

- name: Start and enable chronyd
  systemd:
    name: chronyd
    state: started
    enabled: yes
  tags:
    - software

- name: Set timezone
  timezone:
    name: Asia/Almaty
  notify: reboot
  tags:
    - software
