---

- name: Get package facts
  package_facts:
    manager: auto

- name: Disable SELinux
  selinux:
    state: disabled
  notify: reboot
  tags:
    - software

- name: Remove firewalld package
  yum:
    name: firewalld
    state: absent
  tags:
    - software

- name: Install software
  yum:
    name:
      - epel-release
      - tmux
      - vim
      - curl
      - wget
      - bind-utils
      - git
      - bash-completion
      - iotop
      - strace
      - psmisc
      - python2-cryptography
      - chrony
    state: present
  tags:
    - software

- name: Create directories for certificates
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/kubernetes/pki
    - /etc/kubernetes/pki/etcd
  tags:
    - software

- name: Start and enable chronyd
  systemd:
    name: chronyd
    state: started
    enabled: yes
  tags:
    - software

- name: Set timezone
  timezone:
    name: Asia/Almaty
  notify: reboot
  tags:
    - software
