---

- name: Remove UFW
  apt:
    name: ufw
    state: absent
  tags:
    - software

- name: Install basic software
  apt:
    name:
      - tmux
      - vim
      - curl
      - wget
      - dnsutils
      - git
      - bash-completion
      - iotop
      - strace
      - psmisc
      - chrony
      - python-cryptography
    state: present
  tags:
    - software
