static_resources:
  listeners:
  - address:
      socket_address:
        address: 127.0.0.1
        port_value: 8443
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: kube_api
          cluster: kube_api_servers
          access_log:
            - name: envoy.file_access_log
              config:
                path: /var/log/envoy/access.log
  clusters:
  - name: kube_api_servers
    connect_timeout: 1s
    type: static
    lb_policy: round_robin
    hosts:
{% for host in groups[masters_group_name] %}
    - socket_address:
        address: {{ hostvars[host]['ansible_eth0']['ipv4']['address'] }}
        port_value: 6443
{% endfor %}

admin:
  access_log_path: "/var/log/envoy/admin.log"
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 8001
