---

kube_crt_country_name: KZ
kube_crt_locality_name: Almaty
kube_crt_organization_name: Aviata LLC
kube_crt_organizational_unit_name: Kubernetes
kube_crt_state_or_province_name: Almaty
kube_ca_crt_start_date: 20190101000001Z
kube_ca_crt_expire_date: 20691231235959Z
