---

- name: Generate private keys for Kubernetes master nodes
  openssl_privatekey:
    path: "/etc/ssl/kubernetes/{{ item }}.key"
    size: 2048
    mode: 0644
    backup: yes
  loop: "{{ groups[masters_group_name] }}"
  tags:
    - k8s_generate_crt
    - k8s_generate_crt.kubelet

- name: Generate private keys for Kubernetes worker nodes
  openssl_privatekey:
    path: "/etc/ssl/kubernetes/{{ item }}.key"
    size: 2048
    mode: 0644
    backup: yes
  loop: "{{ groups[workers_group_name] }}"
  tags:
    - k8s_generate_crt
    - k8s_generate_crt.kubelet

- name: Generate CSR for Kubernetes master nodes
  openssl_csr:
    path: /etc/ssl/kubernetes/{{ item }}.csr
    privatekey_path: /etc/ssl/kubernetes/{{ item }}.key
    common_name: "system:node:{{ item }}"
    country_name: "{{ kube_crt_country_name }}"
    locality_name: "{{ kube_crt_locality_name }}"
    organization_name: "system:nodes"
    organizational_unit_name: "{{ kube_crt_organizational_unit_name }}"
    state_or_province_name: "{{ kube_crt_state_or_province_name }}"
    basic_constraints:
      - CA:FALSE
    basic_constraints_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: yes
    extended_key_usage:
      - serverAuth
      - clientAuth
    use_common_name_for_san: no
    subject_alt_name: "DNS:{{ item }},IP:{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    mode: 0644
    backup: yes
  loop: "{{ groups[masters_group_name] }}"
  tags:
    - k8s_generate_crt
    - k8s_generate_crt.kubelet

- name: Generate CSR for Kubernetes worker nodes
  openssl_csr:
    path: /etc/ssl/kubernetes/{{ item }}.csr
    privatekey_path: /etc/ssl/kubernetes/{{ item }}.key
    common_name: "system:node:{{ item }}"
    country_name: "{{ kube_crt_country_name }}"
    locality_name: "{{ kube_crt_locality_name }}"
    organization_name: "system:nodes"
    organizational_unit_name: "{{ kube_crt_organizational_unit_name }}"
    state_or_province_name: "{{ kube_crt_state_or_province_name }}"
    basic_constraints:
      - CA:FALSE
    basic_constraints_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: yes
    extended_key_usage:
      - serverAuth
      - clientAuth
    use_common_name_for_san: no
    subject_alt_name: "DNS:{{ item }},IP:{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    mode: 0644
    backup: yes
  loop: "{{ groups[workers_group_name] }}"
  tags:
    - k8s_generate_crt
    - k8s_generate_crt.kubelet

- name: Generate certificate for Kubernetes master nodes
  openssl_certificate:
    path: /etc/ssl/kubernetes/{{ item }}.crt
    privatekey_path: /etc/ssl/kubernetes/{{ item }}.key
    csr_path: /etc/ssl/kubernetes/{{ item }}.csr
    provider: ownca
    ownca_path: /etc/ssl/kubernetes/ca.crt
    ownca_privatekey_path: /etc/ssl/kubernetes/ca.key
    ownca_not_before: "{{ kube_crt_start_date }}"
    ownca_not_after: "{{ kube_crt_expire_date }}"
    mode: 0644
    backup: yes
  loop: "{{ groups[masters_group_name] }}"
  tags:
    - k8s_generate_crt
    - k8s_generate_crt.kubelet

- name: Generate certificate for Kubernetes worker nodes
  openssl_certificate:
    path: /etc/ssl/kubernetes/{{ item }}.crt
    privatekey_path: /etc/ssl/kubernetes/{{ item }}.key
    csr_path: /etc/ssl/kubernetes/{{ item }}.csr
    provider: ownca
    ownca_path: /etc/ssl/kubernetes/ca.crt
    ownca_privatekey_path: /etc/ssl/kubernetes/ca.key
    ownca_not_before: "{{ kube_crt_start_date }}"
    ownca_not_after: "{{ kube_crt_expire_date }}"
    mode: 0644
    backup: yes
  loop: "{{ groups[workers_group_name] }}"
  tags:
    - k8s_generate_crt
    - k8s_generate_crt.kubelet
