---

- name: Get content of Kubernetes CA certificate
  slurp:
    src: /etc/ssl/kubernetes/ca.crt
  register: kubernetes_ca_crt
  tags:
    - k8s_worker

- name: Get content of Kubernetes Proxy certificate
  slurp:
    src: /etc/ssl/kubernetes/kube-proxy.crt
  register: kubernetes_proxy_crt
  tags:
    - k8s_worker

- name: Get content of Kubernetes Proxy key
  slurp:
    src: /etc/ssl/kubernetes/kube-proxy.key
  register: kubernetes_proxy_key
  tags:
    - k8s_worker

- name: Generate bootstrap kubeconfig
  template:
    src: kubeconfigs/bootstrap.kubeconfig
    dest: "/var/lib/kubernetes/bootstrap.kubeconfig"
    mode: 0644
    backup: yes
  tags:
    - k8s_worker

- name: Generate Kubernetes Proxy kubeconfig
  template:
    src: kubeconfigs/kube-proxy.kubeconfig
    dest: "/var/lib/kubernetes/kube-proxy.kubeconfig"
    mode: 0644
    backup: yes
  tags:
    - k8s_worker
