---

- name: Get content of Kubernetes CA certificate
  slurp:
    src: /etc/ssl/kubernetes/ca.crt
  register: kubernetes_ca_crt
  tags:
    - k8s_worker

- name: Generate bootstrap kubeconfig
  template:
    src: kubeconfigs/bootstrap.kubeconfig
    dest: "/var/lib/kubernetes/bootstrap.kubeconfig"
    mode: 0644
    backup: yes
  tags:
    - k8s_worker
