---

- name: Define cluster_dns_ip
  set_fact:
    cluster_dns_ip: >-
      {%- if cluster_dns_type == "coredns" -%}
      {{ coredns_service_ip }}
      {%- elif cluster_dns_type == "nodelocaldns" -%}
      {{ nodelocaldns_ip }}
      {%- else -%}
      {{ coredns_service_ip }}
      {%- endif -%}

- name: Upload manifest for Kubernetes Proxy
  template:
    src: kube-proxy.yaml
    dest: /etc/kubernetes/manifests/kube-proxy.yaml
  tags:
    - k8s_worker

- name: Upload kubelet-config.yml
  template:
    src: kubelet-config.yaml
    dest: /var/lib/kubelet/kubelet-config.yaml
  notify: restart kubelet
  tags:
    - k8s_worker

- name: Upload systemd configuration
  template:
    src: kubelet.service
    dest: /etc/systemd/system/kubelet.service
  notify: restart kubelet
  tags:
    - k8s_worker
