---

- name: Define cluster_dns_ip
  set_fact:
    cluster_dns_ip: >-
      {%- if cluster_dns_type == "coredns" -%}
      {{ coredns_service_ip }}
      {%- elif cluster_dns_type == "nodelocaldns" -%}
      {{ nodelocaldns_ip }}
      {%- else -%}
      {{ coredns_service_ip }}
      {%- endif -%}

- include: kubernetes.yml
- include: certificates.yml
- include: kubeconfigs.yml
- include: kubelet.yml

- name: Remove temporary files
  file:
    path: "/etc/ssl/kubernetes/{{ item }}"
    state: absent
  loop:
    - ca.csr
    - ca.key
    - front-proxy-ca.csr
    - front-proxy-ca.key
    - sa.crt
    - sa.key
    - etcd/ca.crt
    - etcd/ca.key
    - etcd/ca.csr
  tags:
    - k8s_worker