---

- name: Upload Kubernetes manifests for master node
  template:
    src: "manifests/{{ item }}"
    dest: "/etc/kubernetes/manifests/{{ item }}"
  loop:
    - kube-apiserver-{{ kube_version }}.yaml
    - kube-scheduler-{{ kube_version }}.yaml
    - kube-controller-manager-{{ kube_version }}.yaml
  tags:
    - k8s_master

- name: Upload kube-scheduler.yaml
  copy:
    src: kube-scheduler-{{ kube_version }}.yaml
    dest: /var/lib/kubernetes/kube-scheduler.yaml
  tags:
    - k8s_master
