---

- name: Upload Kubernetes manifests for master node
  template:
    src: "{{ item }}"
    dest: "/etc/kubernetes/manifests/{{ item }}"
  loop:
    - kube-apiserver.yaml
    - kube-scheduler.yaml
    - kube-controller-manager.yaml
    - kube-proxy.yaml
  tags:
    - k8s_master

- name: Upload kube-scheduler.yaml
  copy:
    src: kube-scheduler.yaml
    dest: /var/lib/kubernetes/kube-scheduler.yaml
  tags:
    - k8s_master
