---

- name: Fetch kubelet certificate
  slurp:
    src: /etc/kubernetes/pki/{{ ansible_nodename }}.crt
  register: kubernetes_self_certificate
  tags:
    - k8s_master

- name: Fetch kubelet key
  slurp:
    src: /etc/kubernetes/pki/{{ ansible_nodename }}.key
  register: kubernetes_self_key
  tags:
    - k8s_master

- name: Get content of Kubernetes CA certificate
  slurp:
    src: /etc/kubernetes/pki/ca.crt
  register: kubernetes_ca_crt
  tags:
    - k8s_master

- name: Get content of Kubernetes admin certificate
  slurp:
    src: /etc/kubernetes/pki/admin.crt
  register: kubernetes_admin_crt
  tags:
    - k8s_master

- name: Get content of Kubernetes admin key
  slurp:
    src: /etc/kubernetes/pki/admin.key
  register: kubernetes_admin_key
  tags:
    - k8s_master

- name: Get content of Kubernetes Controller Manager certificate
  slurp:
    src: /etc/kubernetes/pki/controller-manager.crt
  register: kubernetes_controller_manager_crt
  tags:
    - k8s_master

- name: Get content of Kubernetes Controller Manager key
  slurp:
    src: /etc/kubernetes/pki/controller-manager.key
  register: kubernetes_controller_manager_key
  tags:
    - k8s_master

- name: Get content of Kubernetes Proxy certificate
  slurp:
    src: /etc/kubernetes/pki/kube-proxy.crt
  register: kubernetes_proxy_crt
  tags:
    - k8s_master

- name: Get content of Kubernetes Proxy key
  slurp:
    src: /etc/kubernetes/pki/kube-proxy.key
  register: kubernetes_proxy_key
  tags:
    - k8s_master

- name: Get content of Kubernetes Scheduler certificate
  slurp:
    src: /etc/kubernetes/pki/scheduler.crt
  register: kubernetes_scheduler_crt
  tags:
    - k8s_master

- name: Get content of Kubernetes Scheduler key
  slurp:
    src: /etc/kubernetes/pki/scheduler.key
  register: kubernetes_scheduler_key
  tags:
    - k8s_master

- name: Generate kubelet kubeconfig
  template:
    src: kubeconfigs/kubelet.kubeconfig
    dest: "/etc/kubernetes/config/{{ ansible_nodename }}.kubeconfig"
    mode: 0644
    backup: yes
  tags:
    - k8s_master

- name: Generate common kubeconfigs
  template:
    src: "kubeconfigs/{{ item }}"
    dest: "/etc/kubernetes/config/{{ item }}"
    mode: 0644
    backup: yes
  loop:
    - admin.kubeconfig
    - kube-controller-manager.kubeconfig
    - kube-proxy.kubeconfig
    - kube-scheduler.kubeconfig
    - remote.kubeconfig
  tags:
    - k8s_master

- name: Generate root user kubeconfig for cluster management
  template:
    src: kubeconfigs/remote.kubeconfig
    dest: /root/.kube/config
    mode: 0600
  tags:
    - k8s_master
