---

- name: Define cluster_dns_ip
  set_fact:
    cluster_dns_ip: >-
      {%- if cluster_dns_type == "coredns" -%}
      {{ coredns_service_ip }}
      {%- elif cluster_dns_type == "nodelocaldns" -%}
      {{ nodelocaldns_ip }}
      {%- else -%}
      {{ coredns_service_ip }}
      {%- endif -%}

- include: kubernetes.yml
- include: bootstrap_token.yml
- include: encryption_config.yml
- include: certificates.yml
- include: kubeconfigs.yml
- include: components.yml
- include: kubelet.yml
