---

- name: Create directory for certificates
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/ssl/kubernetes
    - /etc/ssl/kubernetes/etcd
  tags:
    - k8s_deploy_crt

- include: etcd.yml
- include: frontproxy.yml
- include: kubernetes.yml
- include: masters.yml
- include: workers.yml
