---

- name: Deploy Kubernetes masters certificates
  copy:
    content: "{{ item.content | b64decode }}"
    dest: "/etc/ssl/kubernetes/{{ item.item }}.crt"
    mode: 0644
  loop: "{{ hostvars[groups[masters_group_name][0]].kubernetes_masters_certificates.results }}"
  tags:
    - k8s_deploy_crt
    - k8s_deploy_crt.masters

- name: Deploy Kubernetes masters keys
  copy:
    content: "{{ item.content | b64decode }}"
    dest: "/etc/ssl/kubernetes/{{ item.item }}.key"
    mode: 0644
  loop: "{{ hostvars[groups[masters_group_name][0]].kubernetes_masters_keys.results }}"
  tags:
    - k8s_deploy_crt
    - k8s_deploy_crt.masters

- name: Deploy Kubernetes masters csrs
  copy:
    content: "{{ item.content | b64decode }}"
    dest: "/etc/ssl/kubernetes/{{ item.item }}.csr"
    mode: 0644
  loop: "{{ hostvars[groups[masters_group_name][0]].kubernetes_masters_csrs.results }}"
  tags:
    - k8s_deploy_crt
    - k8s_deploy_crt.masters
