---

- name: Deploy Kubernetes workers certificates
  copy:
    content: "{{ item.content | b64decode }}"
    dest: "/etc/ssl/kubernetes/{{ item.item }}.crt"
    mode: 0644
  loop: "{{ hostvars[groups['k8s_initial_master'][0]].kubernetes_workers_certificates.results }}"
  tags:
    - k8s_deploy_crt
    - k8s_deploy_crt.workers

- name: Deploy Kubernetes workers keys
  copy:
    content: "{{ item.content | b64decode }}"
    dest: "/etc/ssl/kubernetes/{{ item.item }}.key"
    mode: 0644
  loop: "{{ hostvars[groups['k8s_initial_master'][0]].kubernetes_workers_keys.results }}"
  tags:
    - k8s_deploy_crt
    - k8s_deploy_crt.workers

- name: Deploy Kubernetes workers csrs
  copy:
    content: "{{ item.content | b64decode }}"
    dest: "/etc/ssl/kubernetes/{{ item.item }}.csr"
    mode: 0644
  loop: "{{ hostvars[groups['k8s_initial_master'][0]].kubernetes_workers_csrs.results }}"
  tags:
    - k8s_deploy_crt
    - k8s_deploy_crt.workers
