---

- name: Install epel-release
  yum:
    name: epel-release
    state: present
  tags:
    - containerd
    - containerd.install

- name: Install containerd
  yum:
    name: containerd-{{ containerd_epel_version }}.el7.x86_64
    state: present
  tags:
    - containerd
    - containerd.install
